# Generated by Django 3.0.4 on 2020-04-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='cp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csc_database.CommunityPartner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='event_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='event_name',
            field=models.TextField(blank=True),
        ),
    ]
