# Generated by Django 3.0.4 on 2020-04-14 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0002_auto_20200414_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='volunteers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csc_database.Volunteer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='cp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='csc_database.CommunityPartner'),
        ),
    ]
