# Generated by Django 3.0.4 on 2020-04-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0003_auto_20200414_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceevent',
            name='volunteers',
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='volunteers',
            field=models.ManyToManyField(to='csc_database.Volunteer'),
        ),
    ]
