# Generated by Django 3.0.4 on 2020-04-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0004_auto_20200414_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='service_events',
            field=models.ManyToManyField(to='csc_database.ServiceEvent'),
        ),
    ]
