# Generated by Django 3.0.4 on 2020-04-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0005_volunteer_service_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='class_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='cp_type',
            field=models.CharField(choices=[('Food Justice', 'Food'), ('LGBTQ', 'Lgbtq'), ('Education', 'Education'), ('Racial Equity', 'Equity'), ('Female Empowerment', 'Women')], max_length=100),
        ),
    ]
