# Generated by Django 3.0.4 on 2020-04-14 23:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0006_auto_20200414_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='cp_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='cp_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='cp_mission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='cp_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='cp_service_value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='event_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='event_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='service_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='bu_id',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='class_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='service_events',
            field=models.ManyToManyField(blank=True, to='csc_database.ServiceEvent'),
        ),
    ]
