# Generated by Django 3.0.4 on 2020-04-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0007_auto_20200414_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='cp_type',
            field=models.CharField(choices=[('Food Justice', 'Food'), ('LGBTQ', 'Lgbtq'), ('Education', 'Education'), ('Racial Equity', 'Equity'), ('Gender Equity', 'Gender')], max_length=100),
        ),
    ]
