# Generated by Django 3.0.4 on 2020-04-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0008_auto_20200414_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceevent',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to='csc_database.Volunteer'),
        ),
    ]
