# Generated by Django 3.0.4 on 2020-04-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0009_auto_20200414_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceevent',
            name='volunteers',
        ),
    ]
