# Generated by Django 3.0.4 on 2020-04-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0010_remove_serviceevent_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='capacity',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
