# Generated by Django 3.0.4 on 2020-04-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0012_serviceevent_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceevent',
            name='volunteers',
        ),
    ]
