# Generated by Django 3.0.4 on 2020-04-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0014_serviceevent_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceevent',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='service_date',
            field=models.DateTimeField(),
        ),
    ]
