# Generated by Django 3.0.4 on 2020-04-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0015_auto_20200415_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceevent',
            name='cp',
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='cp',
            field=models.ManyToManyField(to='csc_database.CommunityPartner'),
        ),
    ]
