# Generated by Django 3.0.5 on 2020-04-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0019_auto_20200416_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='service_value',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
            preserve_default=False,
        ),
    ]
