# Generated by Django 3.0.5 on 2020-04-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0020_serviceevent_service_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypartner',
            name='cp_service_value',
        ),
    ]
