# Generated by Django 3.0.5 on 2020-04-18 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0021_remove_communitypartner_cp_service_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceevent',
            name='cp',
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='cp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csc_database.CommunityPartner'),
            preserve_default=False,
        ),
    ]
