# Generated by Django 3.0.5 on 2020-04-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0022_auto_20200418_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='volunteers',
            field=models.ManyToManyField(to='csc_database.Volunteer'),
        ),
    ]
