# Generated by Django 3.0.5 on 2020-04-21 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0023_serviceevent_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceevent',
            name='volunteers',
        ),
    ]
