# Generated by Django 3.0.5 on 2020-04-22 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csc_database', '0025_auto_20200421_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='service_date',
            field=models.DateField(),
        ),
    ]
