# Generated by Django 3.0.4 on 2020-04-14 16:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.TextField(blank=True)),
                ('cp_address', models.TextField(blank=True)),
                ('cp_image', models.ImageField(blank=True, upload_to='')),
                ('cp_mission', models.TextField(blank=True)),
                ('cp_service_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('cp_type', models.CharField(choices=[('Food Justice', 'Food'), ('LGBTQ', 'Lgbtq'), ('Education', 'Education'), ('Racial Equity', 'Equity'), ('Womens Empowerment', 'Women')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bu_id', models.CharField(blank=True, max_length=9)),
                ('pref_service', models.CharField(choices=[('Food Justice', 'Food'), ('LGBTQ', 'Lgbtq'), ('Education', 'Education'), ('Racial Equity', 'Equity'), ('Empowerment of women', 'Womens')], max_length=100)),
            ],
        ),
    ]
