# Generated by Django 3.0.5 on 2020-04-27 03:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypartner',
            name='cp_service_value',
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='cp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.CommunityPartner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='event_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='event_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='service_value',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='class_year',
            field=models.CharField(default=2020, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='service_events',
            field=models.ManyToManyField(blank=True, to='project.ServiceEvent'),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='cp_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='cp_mission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='cp_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='communitypartner',
            name='cp_type',
            field=models.CharField(choices=[('Food Justice', 'Food'), ('LGBTQ', 'Lgbtq'), ('Education', 'Education'), ('Racial Equity', 'Equity'), ('Empowerment of women', 'Womens')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='service_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='bu_id',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
