#.forms.py
#tristan tew
#These are the forms necessary to create mini_fb users, update them
#and create status messages 

from django import forms
from .models import Profile, StatusMessage #import all models

class CreateProfileForm(forms.ModelForm): #this form lays out the necessary fields and categorizes them
    '''A form to create new profiles'''
    first_name = forms.CharField(label="First Name", required=True)
    last_name = forms.CharField(label="Last Name", required=True)
    birth_date = forms.DateField(widget=forms.SelectDateWidget(years=range(2020,1900,-1),), required=True) #given on the assignment page; simplifies birthday entries
    city = forms.CharField(label="City", required=True)
    email_address = forms.EmailField(label="Email Address", required=True) #since this is an email.
    profile_image_url = forms.CharField(label="Profile Image URL", required=True)


    class Meta:
        '''associate this form with the Profile model'''
        model = Profile #connects to models.py
        fields = ['first_name', 'last_name', 'city', 'email_address', 'profile_image_url', 'birth_date',] #includes all data fields lsited above

class UpdateProfileForm(forms.ModelForm):
    '''A form to update old profiles'''

    #both names are omitted per the assignment guidelines; this means that you can change anything but your name on mini fb
    birth_date = forms.DateField(widget=forms.SelectDateWidget(years=range(2020,1900,-1),), required=True) #given on assignment page; lets us add dates for profiles that previously did not have them
    city = forms.CharField(label="City", required=True)
    email_address = forms.EmailField(label="Email Address", required=True)
    profile_image_url = forms.CharField(label="Profile Image URL", required=True)

    class Meta:
        '''associate this form with the Profile model'''
        model = Profile
        fields = ['birth_date', 'city', 'email_address', 'profile_image_url',]

class CreateStatusMessageForm(forms.ModelForm): 
    '''A form to create Status Messages'''

    class Meta:
        '''associate this with the StatusMessage model'''
        model = StatusMessage #ties this to the StatusMessage model instead of profile
        fields = ['message'] #we do not include the timestamp because that is an autogenerated value