from django.db import models
from django.urls import reverse

#file: models.py
#author: Tristan Tew (ttew@bu.edu)
#description: creating the model for the profile to display on mini_fb

# Create your models here.

#This model 

class Profile(models.Model):
    '''Creates the format for the profile model'''

    #data attributes of a mini_fb profile:
    first_name = models.TextField(blank=True)
    last_name = models.TextField(blank=True)
    city = models.TextField(blank=True)
    email_address = models.TextField(blank=True)
    profile_image_url = models.URLField(blank=True)

    #create a string representation of the data

    def __str__(self):
        '''return a string representation of this object'''
        return '%s %s %s %s' % (self.first_name, self.last_name, self.city, self.email_address)

    #New function to tie statuses to individuals
    def get_status_messages(self):
        '''utilizes filtering by pk to group all statuses for a user'''

        statuses = StatusMessage.objects.filter(profile=self.pk)

        return statuses
    
    #Creates a page to for user to see once a profile is created
    def get_absolute_url(self):
        '''Return a URL to display this profile object'''
        return reverse("show_profile_page", kwargs={"pk": self.pk})


class StatusMessage(models.Model):
    '''Create the format for a status message'''

    #data attributes of a status model

    timestamp = models.TimeField(auto_now_add=True) 
    #uses the auto_now_add feature and timefield type to create an autogenerated timestamp
    message = models.TextField(blank=True)
    image = models.ImageField(blank=True)
    
    profile = models.ForeignKey('Profile', on_delete=models.CASCADE,) 
    #uses a foreign key relationship to tie this to the profile and delete when the profile is deleted

    #str method used to create string of the class outputs
    def __str__(self):
        '''return a string representaion of the status update'''
        return '%s %s %s %s' % (self.timestamp, self.message, self.image, self.profile)
