# Generated by Django 3.0.4 on 2020-04-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0006_auto_20200409_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default='1961-12-12'),
            preserve_default=False,
        ),
    ]
