# Generated by Django 3.0.4 on 2020-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0007_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member_since',
            field=models.DateField(auto_now=True),
        ),
    ]
