# Generated by Django 3.0.4 on 2020-04-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0009_auto_20200410_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_since',
            field=models.DateField(auto_now_add=True),
        ),
    ]
