# Generated by Django 3.0.4 on 2020-03-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200328_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='image_url',
        ),
    ]
